### ISSUE TITLE
Invalid version format

### ISSUE THREAD

**Issue by TDSTOS** [CuukyOfficial/VaroPlugin#80]
Everytime I start the plugin it has this error, while checking if a new version was released:

```
[16:41:01 WARN]: java.lang.IllegalArgumentException: Invalid version format
[16:41:01 WARN]:        at de.cuuky.varo.spigot.updater.VaroUpdater.compareVersions(VaroUpdater.java:45)
[16:41:01 WARN]:        at de.cuuky.varo.spigot.updater.VaroUpdater.checkForUpdates(VaroUpdater.java:107)
[16:41:01 WARN]:        at de.cuuky.varo.spigot.updater.VaroUpdater$1.run(VaroUpdater.java:73)
[16:41:01 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[16:41:01 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[16:41:01 WARN]:        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
[16:41:01 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[16:41:01 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[16:41:01 WARN]:        at java.lang.Thread.run(Thread.java:750)
[16:41:01 INFO]: [Varo] Failed to compare versions of plugin id 71075
[16:41:01 INFO]: [Varo] Disabling Varo v4.11.1
[16:41:01 INFO]: [Varo] --------------------------------
[16:41:01 INFO]: [Varo]  
[16:41:01 INFO]: [Varo] Disabling Varo...
[16:41:01 INFO]: [Varo] ----------------------
[16:41:01 INFO]: [Varo] 
[16:41:01 INFO]: [Varo] Plugin Version: 4.11.1
[16:41:01 INFO]: [Varo] Plugins enabled: 14
[16:41:01 INFO]: [Varo] Server-Version: git-PaperSpigot-445 (MC: 1.8.8)
[16:41:01 INFO]: [Varo] System OS: Linux
[16:41:01 INFO]: [Varo] System Version: 5.4.0-105-generic
[16:41:01 INFO]: [Varo] Java Version: 1.8.0_342
[16:41:01 INFO]: [Varo] Total memory usage: 466MB!
[16:41:01 INFO]: [Varo] Total memory available: 6372MB!
[16:41:01 INFO]: [Varo] TPS: 20.0
[16:41:01 INFO]: [Varo] Date: 11.08.2022 16:41
[16:41:01 INFO]: [Varo] 
[16:41:01 INFO]: [Varo] ----------------------
[16:41:01 INFO]: [Varo] Saved Crashreport to bugreport-2022-08-11_16-41-01.zip
[16:41:01 INFO]: [Varo] Disabled! (84ms)
[16:41:01 INFO]: [Varo]  
[16:41:01 INFO]: [Varo] --------------------------------
[16:41:01 INFO]: [Varo] Updater: The plugin is up to date!
```

**Comment by Almighty-Satan** [comment]
Should be fixed now
