### ISSUE TITLE
New cfw implementation causes plugin to crash on startup on server version 1.7.10

### ISSUE THREAD

**Issue by CuukyOfficial** [CuukyOfficial/VaroPlugin#97]
```
java.lang.NoSuchMethodError: 'com.google.common.cache.Cache com.google.common.cache.CacheBuilder.build()'
	at com.cryptomorin.xseries.XMaterial.<clinit>(XMaterial.java:1687) ~[?:?]
	at de.cuuky.varo.configuration.configurations.config.ConfigSettingSection.<clinit>(ConfigSettingSection.java:16) ~[?:?]
	at de.cuuky.varo.configuration.ConfigHandler.loadConfigurations(ConfigHandler.java:36) ~[?:?]
	at de.cuuky.varo.configuration.ConfigHandler.<init>(ConfigHandler.java:32) ~[?:?]
	at de.cuuky.varo.data.DataManager.preLoad(DataManager.java:74) ~[?:?]
	at de.cuuky.varo.Main.onEnable(Main.java:106) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
```

**Comment by Almighty-Satan** [comment]
I know about this, but it's an XSeries issue. I'll make a MR when I have the time and hope they accept it. Otherwise we will have to maintain a fork.

**Comment by Almighty-Satan** [comment]
> I know about this, but it's an XSeries issue. I'll make a MR when I have the time and hope they accept it. Otherwise we will have to maintain a fork.

nvm, fixed via classloader hacks
